import {
  UtensilsCrossed, Coffee, Croissant, Wine, Bike, IceCream, Pizza, Fish,
  Beef, Sandwich, Scissors, Sparkles, Dumbbell, Pill, Stethoscope,
  HeartPulse, ShoppingCart, Store, PawPrint, Shirt, Footprints, Flower2,
  Wrench, Car, WashingMachine, GraduationCap, Tag, Cross, Dog, BookOpen,
  Gem, Smartphone, Hammer, Sofa, Lamp, Building2, Scale, Calculator,
  Landmark, Flame, Salad, CakeSlice, CupSoda, ShoppingBag, HeartHandshake,
  Baby, Blocks, Plug, Droplets, KeyRound, Plane, ShieldCheck, Truck, Package,
  Fuel, Library, BedDouble, Music, Camera, Palette, PartyPopper, Hospital,
  Utensils, Gift,
  type LucideIcon,
} from "lucide-react"

const ICON_BY_SLUG: Record<string, LucideIcon> = {
  restaurantes: UtensilsCrossed,
  cafes: Coffee,
  padarias: Croissant,
  bares: Wine,
  delivery: Bike,
  sorveterias: IceCream,
  pizzarias: Pizza,
  japonesa: Fish,
  hamburguerias: Beef,
  "comida-brasileira": UtensilsCrossed,
  sanduiches: Sandwich,
  "saloes-de-beleza": Sparkles,
  cabelereiros: Scissors,
  barbearias: Scissors,
  manicure: Sparkles,
  spa: Flower2,
  academias: Dumbbell,
  farmacias: Pill,
  dentistas: Stethoscope,
  medicos: Stethoscope,
  fisioterapia: HeartPulse,
  supermercados: ShoppingCart,
  conveniencias: Store,
  "pet-shops": PawPrint,
  moda: Shirt,
  calcados: Footprints,
  floricultura: Flower2,
  mecanicas: Wrench,
  "lava-rapido": Car,
  lavanderias: WashingMachine,
  escolas: GraduationCap,
  clinicas: Cross,
  veterinarias: Dog,
  livrarias: BookOpen,
  joalherias: Gem,
  eletronicos: Smartphone,
  "materiais-construcao": Hammer,
  "casa-decoracao": Lamp,
  moveis: Sofa,
  adegas: Wine,
  imobiliarias: Building2,
  advocacia: Scale,
  contabilidade: Calculator,
  bancos: Landmark,
  // ── novas categorias ──
  churrascarias: Flame,
  "frutos-do-mar": Fish,
  italiana: Pizza,
  mexicana: Utensils,
  vegetariana: Salad,
  "fast-food": Beef,
  doces: CakeSlice,
  sucos: CupSoda,
  buffets: Utensils,
  "praca-alimentacao": Utensils,
  hospitais: Hospital,
  "bem-estar": HeartHandshake,
  estetica: Sparkles,
  mercearias: ShoppingBag,
  presentes: Gift,
  esportes: Bike,
  celulares: Smartphone,
  shoppings: ShoppingBag,
  acougues: Beef,
  cosmeticos: Sparkles,
  "lojas-departamento": Store,
  brinquedos: Blocks,
  bebes: Baby,
  eletricistas: Plug,
  encanadores: Droplets,
  chaveiros: KeyRound,
  "agencias-viagem": Plane,
  seguros: ShieldCheck,
  entregas: Truck,
  mudancas: Package,
  "guarda-moveis": Package,
  costura: Scissors,
  funerarias: Cross,
  creches: Baby,
  postos: Fuel,
  faculdades: GraduationCap,
  bibliotecas: Library,
  autoescolas: Car,
  hospedagem: BedDouble,
  baladas: Music,
  fotografia: Camera,
  galerias: Palette,
  eventos: PartyPopper,
}

/**
 * Ícone da categoria: prioriza o `iconName` escolhido no admin (uma das chaves de
 * ICON_BY_SLUG), depois o mapa por slug, e por fim o genérico (Tag).
 */
export function getCategoryIcon(slug: string, iconName?: string | null): LucideIcon {
  return (iconName ? ICON_BY_SLUG[iconName] : undefined) ?? ICON_BY_SLUG[slug] ?? Tag
}

/** Chaves de ícone disponíveis pro seletor do CRUD de categorias (ordenadas). */
export const ICON_KEYS: string[] = Object.keys(ICON_BY_SLUG).sort()
